server:
  port: 8080
  servlet:
    context-path: /movies-web
  
spring:
  jpa:
    database: "MYSQL"
    show-sql: "true"
    hibernate:
      naming:
        physical-strategy:
          org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    
   
  datasource:
    platform: mysql
    url: "jdbc:mysql://localhost:3306/movieDB"
    username: spring
    password: password1234
    
# Edit to match your own file system
photoTempDir: "/home/ubersfeld/Pictures/tmp/"